// SPDX-License-Identifier: Apache-2.0

package docker

import (
	"bytes"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// copyProjectForCheck copies the project that holds mprPath into a fresh
// temporary directory, so `docker check` can run `mx update-widgets` and
// `mx check` there instead of on the user's project (ako/mxcli#951).
//
// Both tools write into the project they are given: update-widgets rewrites the
// model (and converts MPRv2 to MPRv1), and mx check compiles the theme into
// theme-cache/ and writes deployment/sass/. A snapshot/restore of the v2 storage
// covered only the first half of that, and only on v2 — an MPRv1 project's .mpr
// was rewritten permanently by a "check".
//
// Only what mx reads is copied: build output, caches and VCS metadata are skipped
// (copyProjectTree), so the cost is the model plus the widget, theme and source
// folders. cleanup removes the copy; it is never nil and safe to defer.
func copyProjectForCheck(mprPath string) (workMpr string, cleanup func(), err error) {
	cleanup = func() {}
	abs, err := filepath.Abs(mprPath)
	if err != nil {
		return "", cleanup, err
	}
	tmp, err := os.MkdirTemp("", "mxcli-check-*")
	if err != nil {
		return "", cleanup, err
	}
	cleanup = func() { os.RemoveAll(tmp) }

	projectDir := filepath.Dir(abs)
	dst := filepath.Join(tmp, filepath.Base(projectDir))
	if err := copyProjectTree(projectDir, dst); err != nil {
		cleanup()
		return "", func() {}, err
	}
	return filepath.Join(dst, filepath.Base(abs)), cleanup, nil
}

// checkCopySkipRoot are top-level project folders mx check neither needs nor
// should see: build output and caches it regenerates.
var checkCopySkipRoot = map[string]bool{
	"deployment":    true, // MxBuild / mx check output
	"releases":      true, // exported .mda packages
	"theme-cache":   true, // compiled theme, regenerated by mx check
	".mendix-cache": true,
	".mxcli":        true, // catalog cache, widget docs
	".docker":       true, // docker init output
}

// checkCopySkipAnywhere are folder names skipped at any depth.
var checkCopySkipAnywhere = map[string]bool{
	".git":         true,
	".svn":         true,
	".hg":          true,
	"node_modules": true,
}

// copyProjectTree copies src to dst, skipping the folders above. A symlinked
// file is copied as a file, so a tool writing to the copy cannot write through
// it into the original; a symlinked folder is recreated as a link.
func copyProjectTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			if rel != "." && (checkCopySkipAnywhere[d.Name()] || (!strings.ContainsRune(rel, filepath.Separator) && checkCopySkipRoot[rel])) {
				return filepath.SkipDir
			}
			return os.MkdirAll(target, 0o755)
		}
		if d.Type()&fs.ModeSymlink != 0 {
			info, err := os.Stat(p)
			if err != nil {
				return nil // dangling link: nothing mx could read either
			}
			if info.IsDir() {
				link, err := os.Readlink(p)
				if err != nil {
					return err
				}
				return os.Symlink(link, target)
			}
		} else if !d.Type().IsRegular() {
			return nil // sockets, pipes, devices
		}
		return copyFile(p, target)
	})
}

// pathRewriter forwards output line by line with the temporary copy's path
// replaced by the project's own, so what mx reports names the files the user
// has, not a directory that is deleted when the check ends.
type pathRewriter struct {
	mu   sync.Mutex
	w    io.Writer
	from []string
	to   string
	buf  bytes.Buffer
}

func newPathRewriter(w io.Writer, copyDir, projectDir string) *pathRewriter {
	from := []string{copyDir}
	if resolved, err := filepath.EvalSymlinks(copyDir); err == nil && resolved != copyDir {
		from = append(from, resolved)
	}
	return &pathRewriter{w: w, from: from, to: projectDir}
}

func (r *pathRewriter) Write(p []byte) (int, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.buf.Write(p)
	for {
		i := bytes.IndexByte(r.buf.Bytes(), '\n')
		if i < 0 {
			break
		}
		line := string(r.buf.Next(i + 1))
		if _, err := io.WriteString(r.w, r.rewrite(line)); err != nil {
			return len(p), err
		}
	}
	return len(p), nil
}

// Flush writes a trailing partial line.
func (r *pathRewriter) Flush() {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.buf.Len() > 0 {
		io.WriteString(r.w, r.rewrite(r.buf.String()))
		r.buf.Reset()
	}
}

func (r *pathRewriter) rewrite(s string) string {
	for _, f := range r.from {
		s = strings.ReplaceAll(s, f, r.to)
	}
	return s
}

