// SPDX-License-Identifier: Apache-2.0

package javaactions

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The goldens in testdata/mxbuild are the .java files mxbuild wrote for these
// actions (11.14.0 and 10.24.27 write the same bytes), CRLF and all. mxcli's
// `--watch` hot reload compiles the file mxcli generates, while a full build
// regenerates mxbuild's, so any difference means user code that compiles under
// one breaks under the other: mxcli typed an entity parameter as IMendixObject
// where mxbuild gives the proxy class, an Integer as java.lang.Integer where
// mxbuild gives java.lang.Long, an enumeration as java.lang.Object where
// mxbuild gives the enumeration proxy.
//
// Measured by creating the actions with mxcli on a fresh 11.14.0 app, running
// `mxcli docker build`, and saving what mxbuild left behind. The ones without
// user code below were deleted before that build, so mxbuild generated them
// from nothing.

func ent(qn string) *EntityType  { return &EntityType{Entity: qn} }
func listOf(qn string) *ListType { return &ListType{Entity: qn} }
func param(name string, t CodeActionParameterType) *JavaActionParameter {
	return &JavaActionParameter{Name: name, ParameterType: t}
}

type mxbuildCase struct {
	name     string
	userCode string // "" — generated by mxbuild from no file at all
	params   []*JavaActionParameter
	ret      CodeActionReturnType
}

var mxbuildCases = []mxbuildCase{
	{"JA_Prims", "return 1L;", []*JavaActionParameter{
		param("S", &StringType{}), param("I", &IntegerType{}), param("L", &LongType{}),
		param("D", &DecimalType{}), param("B", &BooleanType{}), param("T", &DateTimeType{}),
	}, &IntegerType{}},
	// Its import list was hand-edited before the build — java.util.List put
	// first, IMendixObject removed — to measure what mxbuild does with an
	// existing list: keeps it in order and appends what is missing.
	{"JA_Ent", "return null;", []*JavaActionParameter{
		param("F", ent("System.FileDocument")), param("Dc", ent("MyFirstModule.Doc")),
		param("Items", listOf("MyFirstModule.Thing")),
	}, ent("MyFirstModule.Doc")},
	{"JA_Enum", "return C == null ? null : C.name();", []*JavaActionParameter{
		param("C", &EnumerationType{Enumeration: "MyFirstModule.Color"}),
	}, &EnumerationType{Enumeration: "MyFirstModule.Color"}},
	// Its import list was emptied before the build: mxbuild appended the three
	// it needs, sorted.
	{"JA_Tpl", "return null;", []*JavaActionParameter{
		param("Q", &StringTemplateParameterType{Grammar: "Sql"}),
		param("X", &StringTemplateParameterType{Grammar: "Text"}),
	}, listOf("MyFirstModule.Thing")},
	{"JA_Ret1", "return null;", []*JavaActionParameter{
		param("URL", &StringType{}), param("aB", &IntegerType{}), param("x", ent("MyFirstModule.Doc")),
		param("MyList", listOf("MyFirstModule.Thing")), param("Cb", &MicroflowType{}),
	}, &DateTimeType{}},
	{"JA_Ret2", "return Obj;", []*JavaActionParameter{
		param("EntityType", &EntityTypeParameterType{TypeParameterName: "pEntity"}),
		param("Obj", &TypeParameter{TypeParameter: "pEntity"}),
	}, &TypeParameter{TypeParameter: "pEntity"}},
	{"JA_Ret3", "return null;", []*JavaActionParameter{
		param("EntityType", &EntityTypeParameterType{TypeParameterName: "pEntity"}),
	}, &ListType{TypeParameter: "pEntity"}},
	// An IMendixObject import it does not need was added before the build:
	// mxbuild kept it.
	{"JA_Ret4", "return null;", nil, &DecimalType{}},
	{"JA_Ret5", "return null;", nil, &StringType{}},
	{"JA_Ret6", "return null;", nil, &VoidType{}},
	{"JA_Ret7", "return null;", nil, &LongType{}},
	{"JA_Generic", "", []*JavaActionParameter{
		param("EntityType", &EntityTypeParameterType{TypeParameterName: "pEntity"}),
		param("Obj", &TypeParameter{TypeParameter: "pEntity"}),
		param("Objs", &ListType{TypeParameter: "pEntity"}),
	}, &BooleanType{}},
	{"JA_Ret8", "", nil, ent("System.FileDocument")},
}

func readGolden(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "mxbuild", name+".java.golden"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "\r\n") {
		t.Fatalf("%s has no CRLF — git normalised the golden; see .gitattributes", name)
	}
	return string(b)
}

// Regenerating over the file mxbuild wrote must give that file back, byte for
// byte: this is the steady state of an mxcli edit followed by a build.
func TestGenerateSource_RegeneratesWhatMxbuildWrote(t *testing.T) {
	for _, c := range mxbuildCases {
		if c.userCode == "" {
			continue
		}
		t.Run(c.name, func(t *testing.T) {
			golden := readGolden(t, c.name)
			imports, extra := RetainSections(golden, nil, "")
			got := GenerateSource("MyFirstModule", c.name, c.userCode, c.params, c.ret, imports, extra)
			if got != golden {
				t.Errorf("generated source differs from mxbuild's:\n%s", lineDiff(golden, got))
			}
		})
	}
}

// With no file to regenerate over, the import list is the one mxbuild writes
// for a new action. The user code is not compared: mxbuild writes a throwing
// stub there, mxcli the statement's body.
func TestGenerateSource_NewFileMatchesMxbuild(t *testing.T) {
	stub := `throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");`
	for _, c := range mxbuildCases {
		if c.userCode != "" {
			continue
		}
		t.Run(c.name, func(t *testing.T) {
			golden := readGolden(t, c.name)
			imports, extra := RetainSections("", nil, "")
			got := GenerateSource("MyFirstModule", c.name, stub, c.params, c.ret, imports, extra)
			// mxcli pads the user code with a blank line on each side.
			got = strings.Replace(got, "// BEGIN USER CODE\r\n\r\n", "// BEGIN USER CODE\r\n", 1)
			got = strings.Replace(got, "\r\n\r\n\t\t// END USER CODE", "\r\n\t\t// END USER CODE", 1)
			if got != golden {
				t.Errorf("generated source differs from mxbuild's:\n%s", lineDiff(golden, got))
			}
		})
	}
}

// lineDiff lists the lines that differ, with line endings made visible.
func lineDiff(want, got string) string {
	w, g := strings.SplitAfter(want, "\n"), strings.SplitAfter(got, "\n")
	var sb strings.Builder
	for i := 0; i < len(w) || i < len(g); i++ {
		var wl, gl string
		if i < len(w) {
			wl = w[i]
		}
		if i < len(g) {
			gl = g[i]
		}
		if wl != gl {
			fmt.Fprintf(&sb, "line %d\n  mxbuild: %q\n  mxcli:   %q\n", i+1, wl, gl)
		}
	}
	return sb.String()
}
