// SPDX-License-Identifier: Apache-2.0

package javaactions

import (
	"reflect"
	"strings"
	"testing"
)

// The banner Studio Pro writes at the top of every Java action is the contract:
// "Only the following code will be retained when actions are regenerated: the
// import list, the code between BEGIN USER CODE and END USER CODE, the code
// between BEGIN EXTRA CODE and END EXTRA CODE". mxcli's regeneration kept only
// the user code, so rewriting an action whose user code calls a helper in its
// EXTRA CODE section — the Blank template's FeedbackModule.XSS_Sanitizer calls
// sanitize() — produced Java that does not compile (ako/mxcli#705). MDL has no
// spelling for extra code, so it can only be retained.
const studioProSource = `// This file was generated by Mendix Studio Pro.

package feedbackmodule.actions;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.UserAction;

public class XSS_Sanitizer extends UserAction<java.lang.String>
{
	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return sanitize(stringToSanitize);
		// END USER CODE
	}

	// BEGIN EXTRA CODE
    public static String sanitize(String input) {
        return input;
    }
	// END EXTRA CODE
}
`

func TestRetainedSections_ReadsImportsAndExtraCode(t *testing.T) {
	imports, extra := RetainedSections(studioProSource)
	want := []string{
		"import java.util.regex.Matcher;",
		"import java.util.regex.Pattern;",
		"import com.mendix.webui.CustomJavaAction;",
	}
	if !reflect.DeepEqual(imports, want) {
		t.Errorf("imports = %q, want %q (the two the generator writes itself left out)", imports, want)
	}
	if !strings.Contains(extra, "public static String sanitize(String input)") {
		t.Errorf("extra code = %q, want the sanitize helper", extra)
	}
}

func TestRetainSections_MergesWithWhatTheStatementSaid(t *testing.T) {
	imports, extra := RetainSections(studioProSource,
		[]string{"import java.util.regex.Pattern;", "import java.util.List;"}, "")
	// The stored list as it stands — mxbuild neither reorders it nor moves the
	// imports it generates itself to the top — plus the new one.
	want := []string{
		"import java.util.regex.Matcher;",
		"import java.util.regex.Pattern;",
		"import com.mendix.systemwideinterfaces.core.IContext;",
		"import com.mendix.webui.CustomJavaAction;",
		"import com.mendix.systemwideinterfaces.core.UserAction;",
		"import java.util.List;",
	}
	if !reflect.DeepEqual(imports, want) {
		t.Errorf("imports = %q, want the stored list plus the new one, without duplicates: %q", imports, want)
	}
	if !strings.Contains(extra, "sanitize") {
		t.Errorf("extra code = %q — a statement that cannot say anything about extra code deleted it", extra)
	}

	// Extra code the statement DOES provide wins.
	if _, extra := RetainSections(studioProSource, nil, "int x;"); extra != "int x;" {
		t.Errorf("extra code = %q, want the authored one", extra)
	}
	// No existing file: only what the statement said.
	if imports, extra := RetainSections("", []string{"import a.B;"}, ""); !reflect.DeepEqual(imports, []string{"import a.B;"}) || extra != "" {
		t.Errorf("no existing file: got %q / %q", imports, extra)
	}
}

// End to end through the generator: the regenerated file compiles against the
// same helper and imports.
func TestGenerateSource_WithRetainedSectionsKeepsTheHelper(t *testing.T) {
	imports, extra := RetainSections(studioProSource, nil, "")
	src := GenerateSource("FeedbackModule", "XSS_Sanitizer", "return sanitize(stringToSanitize);",
		nil, &StringType{}, imports, extra)
	for _, want := range []string{
		"import java.util.regex.Pattern;",
		"public static String sanitize(String input) {",
		"return sanitize(stringToSanitize);",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("regenerated source lacks %q:\n%s", want, src)
		}
	}
	if n := strings.Count(src, "import com.mendix.systemwideinterfaces.core.IContext;"); n != 1 {
		t.Errorf("IContext imported %d times, want 1", n)
	}
}
