// SPDX-License-Identifier: Apache-2.0

package javaactions

import (
	"fmt"
	"sort"
	"strings"
)

// The imports every generated action needs, and the one it needs when a
// parameter or the return type is an object or a list of them.
const (
	importIContext      = "import com.mendix.systemwideinterfaces.core.IContext;"
	importUserAction    = "import com.mendix.systemwideinterfaces.core.UserAction;"
	importIMendixObject = "import com.mendix.systemwideinterfaces.core.IMendixObject;"
)

// GenerateSource renders the .java stub for a Java action — package, imports,
// parameter fields + constructor, the executeAction method wrapping the user
// code, toString, and the extra-code section — exactly as mxbuild generates it,
// CRLF line endings included.
//
// It has to be exact, not merely equivalent: mxcli's `--watch` hot reload
// compiles the file mxcli writes, and the next full build regenerates mxbuild's
// over it, so user code written against one must compile against the other. An
// object parameter's field is its proxy class (the raw IMendixObject is kept in
// a deprecated `__Name` field), an Integer is a java.lang.Long, an enumeration
// is its proxy enum — measured on 10.24.27 and 11.14.0, which write the same
// bytes (testdata/mxbuild).
//
// imports is the import list to keep, in order — the existing file's, see
// RetainSections. The imports the generated code needs and the list lacks are
// appended, sorted. That is what mxbuild does: it never reorders or drops an
// import, so for a new file it writes just the needed ones, sorted.
func GenerateSource(moduleName, actionName string, userCode string, params []*JavaActionParameter, returnType CodeActionReturnType, imports []string, extraCode string) string {
	moduleNameLower := strings.ToLower(moduleName)
	returnTypeStr := javaReturnType(returnType)

	var sb strings.Builder

	sb.WriteString("// This file was generated by Mendix Studio Pro.\n")
	sb.WriteString("//\n")
	sb.WriteString("// WARNING: Only the following code will be retained when actions are regenerated:\n")
	sb.WriteString("// - the import list\n")
	sb.WriteString("// - the code between BEGIN USER CODE and END USER CODE\n")
	sb.WriteString("// - the code between BEGIN EXTRA CODE and END EXTRA CODE\n")
	sb.WriteString("// Other code you write will be lost the next time you deploy the project.\n")
	sb.WriteString("// Special characters, e.g., é, ö, à, etc. are supported in comments.\n\n")

	sb.WriteString(fmt.Sprintf("package %s.actions;\n\n", moduleNameLower))

	for _, imp := range completeImports(imports, params, returnType) {
		sb.WriteString(imp)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("public class %s extends UserAction<%s>\n", actionName, returnTypeStr))
	sb.WriteString("{\n")

	for _, param := range params {
		javaType := javaParamType(param.ParameterType)
		switch proxy := proxyType(param.ParameterType); {
		case proxy == "":
			sb.WriteString(fmt.Sprintf("\tprivate final %s %s;\n", fieldType(param.ParameterType), param.Name))
		case isList(param.ParameterType):
			sb.WriteString(fmt.Sprintf("\t/** @deprecated use com.mendix.utils.ListUtils.map(%s, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */\n", param.Name))
			sb.WriteString("\t@java.lang.Deprecated(forRemoval = true)\n")
			sb.WriteString(fmt.Sprintf("\tprivate final %s __%s;\n", javaType, param.Name))
			sb.WriteString(fmt.Sprintf("\tprivate final java.util.List<%s> %s;\n", proxy, param.Name))
		default:
			sb.WriteString(fmt.Sprintf("\t/** @deprecated use %s.getMendixObject() instead. */\n", param.Name))
			sb.WriteString("\t@java.lang.Deprecated(forRemoval = true)\n")
			sb.WriteString(fmt.Sprintf("\tprivate final %s __%s;\n", javaType, param.Name))
			sb.WriteString(fmt.Sprintf("\tprivate final %s %s;\n", proxy, param.Name))
		}
	}

	if len(params) == 0 {
		sb.WriteString(fmt.Sprintf("\tpublic %s(IContext context)\n", actionName))
	} else {
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("\tpublic %s(\n", actionName))
		sb.WriteString("\t\tIContext context")
		for _, param := range params {
			sb.WriteString(fmt.Sprintf(",\n\t\t%s _%s", javaParamType(param.ParameterType), lowerFirst(param.Name)))
		}
		sb.WriteString("\n\t)\n")
	}
	sb.WriteString("\t{\n")
	sb.WriteString("\t\tsuper(context);\n")
	for _, param := range params {
		arg := "_" + lowerFirst(param.Name)
		switch proxy := proxyType(param.ParameterType); {
		case proxy == "" && enumProxy(param.ParameterType) != "":
			sb.WriteString(fmt.Sprintf("\t\tthis.%s = %s == null ? null : %s.valueOf(%s);\n", param.Name, arg, enumProxy(param.ParameterType), arg))
		case proxy == "":
			sb.WriteString(fmt.Sprintf("\t\tthis.%s = %s;\n", param.Name, arg))
		case isList(param.ParameterType):
			element := lowerFirst(param.Name) + "Element"
			sb.WriteString(fmt.Sprintf("\t\tthis.__%s = %s;\n", param.Name, arg))
			sb.WriteString(fmt.Sprintf("\t\tthis.%s = java.util.Optional.ofNullable(%s)\n", param.Name, arg))
			sb.WriteString("\t\t\t.orElse(java.util.Collections.emptyList())\n")
			sb.WriteString("\t\t\t.stream()\n")
			sb.WriteString(fmt.Sprintf("\t\t\t.map(%s -> %s.initialize(getContext(), %s))\n", element, proxy, element))
			sb.WriteString("\t\t\t.collect(java.util.stream.Collectors.toList());\n")
		default:
			sb.WriteString(fmt.Sprintf("\t\tthis.__%s = %s;\n", param.Name, arg))
			sb.WriteString(fmt.Sprintf("\t\tthis.%s = %s == null ? null : %s.initialize(getContext(), %s);\n", param.Name, arg, proxy, arg))
		}
	}
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString(fmt.Sprintf("\tpublic %s executeAction() throws Exception\n", returnTypeStr))
	sb.WriteString("\t{\n")
	sb.WriteString("\t\t// BEGIN USER CODE\n")
	sb.WriteString("\n")
	for line := range strings.SplitSeq(userCode, "\n") {
		sb.WriteString("\t\t")
		sb.WriteString(line)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
	sb.WriteString("\t\t// END USER CODE\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t/**\n")
	sb.WriteString("\t * Returns a string representation of this action\n")
	sb.WriteString("\t * @return a string representation of this action\n")
	sb.WriteString("\t */\n")
	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString("\tpublic java.lang.String toString()\n")
	sb.WriteString("\t{\n")
	sb.WriteString(fmt.Sprintf("\t\treturn \"%s\";\n", actionName))
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// BEGIN EXTRA CODE\n")
	if extraCode != "" {
		for line := range strings.SplitSeq(extraCode, "\n") {
			sb.WriteString("\t")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\t// END EXTRA CODE\n")
	sb.WriteString("}\n")

	// mxbuild writes CRLF, and rewrites an LF file that is otherwise identical,
	// so LF here would make the first build after every mxcli edit touch the
	// file again. User and extra code may arrive with either ending.
	src := strings.ReplaceAll(sb.String(), "\r\n", "\n")
	return strings.ReplaceAll(src, "\n", "\r\n")
}

// completeImports returns imports, deduplicated, with the ones the generated
// code needs and imports lacks appended in sorted order.
func completeImports(imports []string, params []*JavaActionParameter, returnType CodeActionReturnType) []string {
	needed := []string{importIContext, importUserAction}
	usesObject := strings.Contains(javaReturnType(returnType), "IMendixObject")
	for _, p := range params {
		usesObject = usesObject || strings.Contains(javaParamType(p.ParameterType), "IMendixObject")
	}
	if usesObject {
		needed = append(needed, importIMendixObject)
	}
	sort.Strings(needed)

	out := make([]string, 0, len(imports)+len(needed))
	seen := make(map[string]bool, len(imports)+len(needed))
	for _, imp := range imports {
		if imp = strings.TrimSpace(imp); imp != "" && !seen[imp] {
			seen[imp] = true
			out = append(out, imp)
		}
	}
	for _, imp := range needed {
		if !seen[imp] {
			out = append(out, imp)
		}
	}
	return out
}

// javaReturnType maps a return type to the Java type mxbuild declares for it.
func javaReturnType(t CodeActionReturnType) string {
	switch t.(type) {
	case nil, *BooleanType:
		return "java.lang.Boolean"
	case *VoidType:
		return "java.lang.Void"
	case *IntegerType, *LongType:
		// Mendix's Integer is 64-bit; mxbuild declares both as Long.
		return "java.lang.Long"
	case *DecimalType:
		return "java.math.BigDecimal"
	case *StringType, *EnumerationType:
		// An enumeration is returned as its value's name.
		return "java.lang.String"
	case *DateTimeType:
		return "java.util.Date"
	case *EntityType, *FileDocumentType, *TypeParameter:
		return "IMendixObject"
	case *ListType:
		return "java.util.List<IMendixObject>"
	default:
		return "java.lang.Object"
	}
}

// javaParamType maps a parameter type to the Java type of its constructor
// argument — for an object or list parameter also its deprecated raw `__`
// field; fieldType and proxyType give the field the user code reads.
func javaParamType(t CodeActionParameterType) string {
	switch t.(type) {
	case *BooleanType:
		return "java.lang.Boolean"
	case *IntegerType, *LongType:
		return "java.lang.Long"
	case *DecimalType:
		return "java.math.BigDecimal"
	case *StringType, *StringTemplateParameterType, *MicroflowType, *EnumerationType, *EntityTypeParameterType:
		// A microflow arrives as its qualified name, an entity type selector as
		// the entity's, an enumeration as its value's name.
		return "java.lang.String"
	case *DateTimeType:
		return "java.util.Date"
	case *EntityType, *FileDocumentType, *TypeParameter:
		return "IMendixObject"
	case *ListType:
		return "java.util.List<IMendixObject>"
	default:
		return "java.lang.Object"
	}
}

// fieldType is the type of a parameter's field when it has no proxy class: the
// constructor argument's, except an enumeration's, which is its proxy enum.
func fieldType(t CodeActionParameterType) string {
	if e := enumProxy(t); e != "" {
		return e
	}
	return javaParamType(t)
}

// proxyType is the proxy class an object parameter's field is typed as — for a
// list, its element's — or "" when the field keeps the argument's type: a
// primitive, an enumeration, or an object of a type parameter, which has no
// class to name.
func proxyType(t CodeActionParameterType) string {
	switch v := t.(type) {
	case *EntityType:
		return proxyClass(v.Entity)
	case *FileDocumentType:
		return proxyClass("System.FileDocument")
	case *ListType:
		if v.TypeParameter != "" || v.TypeParameterID != "" {
			return ""
		}
		return proxyClass(v.Entity)
	}
	return ""
}

func isList(t CodeActionParameterType) bool {
	_, ok := t.(*ListType)
	return ok
}

// enumProxy is the proxy enum of an enumeration parameter, "" for any other.
func enumProxy(t CodeActionParameterType) string {
	if e, ok := t.(*EnumerationType); ok {
		return proxyClass(e.Enumeration)
	}
	return ""
}

// proxyClass maps Module.Name to its generated proxy class, module.proxies.Name.
func proxyClass(qualifiedName string) string {
	module, name, ok := strings.Cut(qualifiedName, ".")
	if !ok || module == "" || name == "" {
		return ""
	}
	return strings.ToLower(module) + ".proxies." + name
}

// lowerFirst lower-cases the first character only, the way mxbuild names a
// constructor argument: URL -> _uRL.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
