// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// init_tooling_sync.go extends the session-start refresh beyond the skills to
// the rest of what `mxcli init` writes from the binary: the bundled lint rules
// and the mxcli-owned part of CLAUDE.md / AGENTS.md (ako/mxcli#952).
//
// Before this, `init --sync-skills` refreshed only the skills. A project kept
// the lint rules and CLAUDE.md of whichever mxcli first initialised it, so
// after an upgrade the guidance and the rules disagreed with the binary in
// exactly the way the skills sync was written to prevent.

// Markers delimiting the part of a generated markdown file mxcli owns. Matched
// by prefix, so the wording of the begin line can change without orphaning
// the files that carry an older one.
const (
	mxcliSectionBeginPrefix = "<!-- mxcli:begin"
	mxcliSectionBegin       = "<!-- mxcli:begin — generated by mxcli and refreshed by 'mxcli init --sync-skills'. Edit outside these markers; anything between them is replaced. -->"
	mxcliSectionEnd         = "<!-- mxcli:end -->"
)

// ownedDocs are the generated markdown files whose mxcli section is kept
// current. Each is refreshed only when it already exists: the sync never
// creates a file `mxcli init` did not (a Cursor-only project has no CLAUDE.md,
// and must not grow one).
func ownedDocs() []ToolFile {
	var docs []ToolFile
	for _, f := range SupportedTools["claude"].Files {
		if f.Path == "CLAUDE.md" {
			docs = append(docs, f)
		}
	}
	return append(docs, UniversalFiles...)
}

// isOwnedDoc reports whether init should write path through the markers.
func isOwnedDoc(path string) bool {
	for _, d := range ownedDocs() {
		if d.Path == path {
			return true
		}
	}
	return false
}

// wrapMxcliSection puts generated content between the markers.
func wrapMxcliSection(generated string) string {
	if !strings.HasSuffix(generated, "\n") {
		generated += "\n"
	}
	return mxcliSectionBegin + "\n" + generated + mxcliSectionEnd + "\n"
}

// mergeMxcliSection replaces the marked section of existing with generated,
// keeping every byte outside the markers. ok is false when existing has no
// well-formed marker pair, in which case nothing can be told apart and the
// caller must not write.
func mergeMxcliSection(existing, generated string) (out string, ok bool) {
	begin := lineStartingWith(existing, mxcliSectionBeginPrefix, 0)
	if begin < 0 {
		return "", false
	}
	end := lineStartingWith(existing, mxcliSectionEnd, begin)
	if end < 0 {
		return "", false
	}
	after := end + len(mxcliSectionEnd)
	// Consume the rest of the end-marker line, including its newline.
	if nl := strings.IndexByte(existing[after:], '\n'); nl >= 0 {
		after += nl + 1
	} else {
		after = len(existing)
	}
	return existing[:begin] + wrapMxcliSection(generated) + existing[after:], true
}

// lineStartingWith returns the offset of the first line at or after from that
// begins with prefix, or -1.
func lineStartingWith(s, prefix string, from int) int {
	for i := from; i < len(s); {
		if (i == 0 || s[i-1] == '\n') && strings.HasPrefix(s[i:], prefix) {
			return i
		}
		nl := strings.IndexByte(s[i:], '\n')
		if nl < 0 {
			break
		}
		i += nl + 1
	}
	return -1
}

// docWriteResult is what writing one owned doc did.
type docWriteResult int

const (
	docUnchanged docWriteResult = iota
	docWritten
	docNoMarkers // exists without markers; left alone
)

// writeOwnedDoc writes the generated content of an mxcli-owned markdown file.
//
// A file with markers has only its marked section replaced. A file without
// them predates the markers: `mxcli init` regenerates it whole, as it always
// has (adopting the markers from then on), while the unattended sync leaves it
// untouched — it cannot tell mxcli's text from the project's, and a refresh
// that runs on every session start must never be the thing that deletes a
// project's notes.
func writeOwnedDoc(path, generated string, fromInit bool) (docWriteResult, error) {
	existing, err := os.ReadFile(path)
	var want string
	switch {
	case os.IsNotExist(err):
		if !fromInit {
			return docUnchanged, nil
		}
		want = wrapMxcliSection(generated)
	case err != nil:
		return docUnchanged, err
	default:
		merged, ok := mergeMxcliSection(string(existing), generated)
		switch {
		case ok:
			want = merged
		case fromInit:
			want = wrapMxcliSection(generated)
		default:
			return docNoMarkers, nil
		}
		if want == string(existing) {
			return docUnchanged, nil
		}
	}
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return docUnchanged, fmt.Errorf("writing %s: %w", path, err)
	}
	return docWritten, nil
}

// bundledLintRuleNames lists the rule files this binary ships, by file name.
// The name IS the marker of a bundled rule: a project's own rules live beside
// them in the same directory under other names, and are never touched.
func bundledLintRuleNames() ([]string, error) {
	var names []string
	err := fs.WalkDir(lintRulesFS, "lint-rules", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			names = append(names, d.Name())
		}
		return nil
	})
	sort.Strings(names)
	return names, err
}

// syncBundledLintRules rewrites the bundled rules in a project's lint-rules
// directory from the binary, returning the names that differed. A missing
// directory means the project was not initialised with a tool that uses the
// rules, and stays missing.
//
// An edit to a bundled rule file is overwritten — the file belongs to mxcli,
// like a skill. To change one, copy it under a new name (and a new rule ID),
// or override it in lint-config.yaml.
func syncBundledLintRules(lintRulesDir string) ([]string, error) {
	if st, err := os.Stat(lintRulesDir); err != nil || !st.IsDir() {
		return nil, nil
	}
	names, err := bundledLintRuleNames()
	if err != nil {
		return nil, err
	}
	var changed []string
	for _, name := range names {
		want, err := lintRulesFS.ReadFile("lint-rules/" + name)
		if err != nil {
			return changed, err
		}
		target := filepath.Join(lintRulesDir, name)
		if have, readErr := os.ReadFile(target); readErr == nil && bytes.Equal(have, want) {
			continue
		}
		if err := os.WriteFile(target, want, 0o644); err != nil {
			return changed, fmt.Errorf("writing %s: %w", target, err)
		}
		changed = append(changed, name)
	}
	return changed, nil
}

// toolingSyncResult reports a full tooling refresh.
type toolingSyncResult struct {
	Skills       skillSyncResult
	LintRules    []string // bundled rule files rewritten
	Docs         []string // owned docs whose mxcli section was rewritten
	NoMarkers    []string // owned docs left alone: no markers to refresh between
	StampWritten bool
	// RefusedFor is set when the sync did nothing because this binary is older
	// than the one that wrote the tooling.
	RefusedFor *toolingStamp
}

// syncProjectTooling is `mxcli init --sync-skills`: refresh everything init
// derives from the binary, without touching what the project wrote.
//
// It refuses outright when the running binary is older than the stamp. The
// refresh is a copy from the binary, so running it from an older one is a
// downgrade — the skills, the rules and CLAUDE.md all moved back to what the
// old binary knows, silently, on the next session start. Updating the binary is
// the fix; rolling the project back to match it is not.
func syncProjectTooling(projectDir string) (toolingSyncResult, error) {
	var res toolingSyncResult
	if s := staleBinaryStamp(projectDir); s != nil {
		res.RefusedFor = s
		return res, nil
	}

	skills, err := syncAIContextSkills(projectDir)
	if err != nil {
		return res, fmt.Errorf("syncing skills: %w", err)
	}
	res.Skills = skills

	if res.LintRules, err = syncBundledLintRules(filepath.Join(projectDir, ".claude", "lint-rules")); err != nil {
		return res, fmt.Errorf("syncing lint rules: %w", err)
	}

	// The docs embed the .mpr path, so without one there is nothing correct to
	// render; init would write a placeholder, a refresh must not.
	if mprFile := findMprFile(projectDir); mprFile != "" {
		projectName := filepath.Base(projectDir)
		for _, doc := range ownedDocs() {
			r, err := writeOwnedDoc(filepath.Join(projectDir, doc.Path), doc.Content(projectName, mprFile), false)
			if err != nil {
				return res, err
			}
			switch r {
			case docWritten:
				res.Docs = append(res.Docs, doc.Path)
			case docNoMarkers:
				res.NoMarkers = append(res.NoMarkers, doc.Path)
			}
		}
	}

	if res.StampWritten, err = writeToolingStamp(projectDir); err != nil {
		return res, err
	}
	return res, nil
}

// reportToolingSync prints what the refresh did — nothing at all when the
// project was already current, since this runs on every session start. The
// refusal and the marker notice go to errw: they are about the setup, not the
// refresh, and must be visible even when stdout is discarded.
func reportToolingSync(w, errw io.Writer, res toolingSyncResult) {
	if res.RefusedFor != nil {
		fmt.Fprintf(errw, "Not syncing: this mxcli (%s) is older than the mxcli that wrote this project's tooling (%s);\n",
			currentMxcliVersion(), res.RefusedFor.Version)
		fmt.Fprintln(errw, "  a sync from it would downgrade the skills, lint rules and CLAUDE.md. Update mxcli instead:")
		fmt.Fprintf(errw, "  ./mxcli setup mxcli --tag %s --output ./mxcli, or delete ./mxcli and run: sh %s\n",
			updateTag(res.RefusedFor.Version), bootstrapScriptName)
		return
	}
	reportSkillSync(w, res.Skills)
	if len(res.LintRules) > 0 {
		fmt.Fprintf(w, "Refreshed %d bundled lint rule(s) in .claude/lint-rules/ to match this mxcli: %s\n",
			len(res.LintRules), abridge(res.LintRules))
	}
	if len(res.Docs) > 0 {
		fmt.Fprintf(w, "Refreshed the mxcli section of %s\n", strings.Join(res.Docs, ", "))
	}
	if len(res.NoMarkers) > 0 {
		fmt.Fprintf(errw, "Note: %s %s no mxcli section markers, so %s not refreshed. Run 'mxcli init' once to adopt them\n",
			strings.Join(res.NoMarkers, ", "), map[bool]string{true: "has", false: "have"}[len(res.NoMarkers) == 1],
			map[bool]string{true: "it was", false: "they were"}[len(res.NoMarkers) == 1])
		fmt.Fprintln(errw, "  (it regenerates the file; keep project notes outside the markers from then on).")
	}
}

// mdlsourceReadme seeds mdlsource/, the directory the generated CLAUDE.md
// says scripts live in. Without it the first script had nowhere obvious to go.
const mdlsourceReadme = `# mdlsource

MDL scripts for this project, one file per concern. Each starts with ` + "`mdl 1;`" + `.

    ./mxcli check mdlsource/<file>.mdl -p <project>.mpr
    ./mxcli exec  mdlsource/<file>.mdl -p <project>.mpr

Exec a change twice: the second run must write nothing.
`

// ensureMdlsourceDir creates mdlsource/ with a README so the directory
// survives git (which does not track empty directories). An existing README
// is left alone.
func ensureMdlsourceDir(projectDir string) (created bool, err error) {
	dir := filepath.Join(projectDir, "mdlsource")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, err
	}
	readme := filepath.Join(dir, "README.md")
	if _, err := os.Stat(readme); err == nil {
		return false, nil
	}
	if err := os.WriteFile(readme, []byte(mdlsourceReadme), 0o644); err != nil {
		return false, err
	}
	return true, nil
}
