// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// init_hook.go emits a Claude Code SessionStart hook into .claude/settings.json so
// a fresh (or reaped-and-resumed) session self-bootstraps: it caches MxBuild +
// runtime and provisions the local database, leaving the session ready to
// `mxcli run --local`. Background processes (Postgres, the JVM) are reaped on
// idle, so this idempotent bring-up must run on every session start.
//
// The hook is setup-only (non-blocking): it must return, so it prepares
// prerequisites and exits rather than booting the long-lived warm loop.

// bootstrapScriptName is the committed script the SessionStart hook runs,
// relative to the project root.
const bootstrapScriptName = ".claude/bootstrap-mxcli.sh"

// bootstrapScriptTemplate is written to bootstrapScriptName. %s is the .mpr file
// name. It is POSIX sh (no bashisms) and safe to re-run: every step is a no-op
// once satisfied.
//
// It is COMMITTED on purpose — the opposite of the mxcli binary, which
// .gitignore excludes for its size. After an idle reap the container is
// reclaimed and the repo re-cloned, and this file is then the only thing in the
// tree that can bring the binary back.
const bootstrapScriptTemplate = `#!/bin/sh
# Generated by 'mxcli init'. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: fetch mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~85 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# Pin a specific mxcli with MXCLI_TAG=vX.Y.Z (default: nightly).
#
# Version guard: .ai-context/mxcli-tooling.json records the mxcli that wrote
# this project's tooling (CLAUDE.md, skills, lint rules). A binary older than
# that does not understand all of it, so an older ./mxcli is replaced and an
# older mxcli on PATH is not linked in. Only a provable "older" counts: dev
# builds and unknown versions are never second-guessed. Binaries that predate
# the stamp cannot check it themselves — this script is where the check lives
# for them.
set -e

MPR='%s'
TAG="${MXCLI_TAG:-nightly}"
STAMP=.ai-context/mxcli-tooling.json

# stamp_field KEY: a string field of the tooling stamp, or nothing.
stamp_field() {
  [ -f "$STAMP" ] || return 0
  sed -n "s/.*\"$1\": *\"\([^\"]*\)\".*/\1/p" "$STAMP" | head -n 1
}

# ymd TIMESTAMP: 2026-10-01T12:00:00Z -> 20261001, anything else -> nothing.
ymd() {
  echo "$1" | sed -n 's/^\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)T.*/\1\2\3/p'
}

# bin_version BINARY / bin_built BINARY: what 'BINARY --version' reports.
bin_version() {
  MXCLI_QUIET=1 "$1" --version 2>/dev/null | sed -n 's/^mxcli version \([^ ]*\).*/\1/p' | head -n 1
}
bin_built() {
  ymd "$(MXCLI_QUIET=1 "$1" --version 2>/dev/null | sed -n 's/^mxcli version [^ ]* (\(.*\))$/\1/p' | head -n 1)"
}

# vclass VERSION: "r MAJOR MINOR PATCH" for a release tag, "n YYYYMMDD" for a
# nightly tag, "u" for anything else (dev builds: v0.24.0-888-g4ba1495f2).
vclass() {
  case "$1" in
    nightly-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-*)
      echo "n $(echo "$1" | cut -d- -f2)" ;;
    *)
      r=$(echo "$1" | sed -n 's/^v\{0,1\}\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)$/r \1 \2 \3/p')
      if [ -n "$r" ]; then echo "$r"; else echo u; fi ;;
  esac
}

# version_lt HAVE HAVE_BUILT WANT WANT_BUILT: succeeds when HAVE is provably
# older than WANT. Releases compare by number, nightlies by tag date, and a
# release against a nightly by build date (YYYYMMDD), when both are known.
version_lt() {
  hc=$(vclass "$1"); wc=$(vclass "$3"); hb=$2; wb=$4
  [ "$hc" = u ] && return 1
  [ "$wc" = u ] && return 1
  hk=$(echo "$hc" | cut -d' ' -f1); wk=$(echo "$wc" | cut -d' ' -f1)
  if [ "$hk" = r ] && [ "$wk" = r ]; then
    set -- $(echo "$hc" | cut -d' ' -f2-) $(echo "$wc" | cut -d' ' -f2-)
    [ "$1" -lt "$4" ] && return 0
    [ "$1" -gt "$4" ] && return 1
    [ "$2" -lt "$5" ] && return 0
    [ "$2" -gt "$5" ] && return 1
    [ "$3" -lt "$6" ]
    return
  fi
  [ "$hk" = n ] && hb=$(echo "$hc" | cut -d' ' -f2)
  [ "$wk" = n ] && wb=$(echo "$wc" | cut -d' ' -f2)
  [ -n "$hb" ] && [ -n "$wb" ] && [ "$hb" -lt "$wb" ]
}

# older_than_stamp BINARY: succeeds when BINARY is provably older than the
# mxcli that wrote this project's tooling.
older_than_stamp() {
  want=$(stamp_field version)
  [ -n "$want" ] || return 1
  have=$(bin_version "$1")
  [ -n "$have" ] || return 1
  version_lt "$have" "$(bin_built "$1")" "$want" "$(ymd "$(stamp_field built)")"
}

stale=
if [ -x ./mxcli ] && older_than_stamp ./mxcli; then
  echo "./mxcli is $(bin_version ./mxcli), older than the mxcli that wrote this project's tooling ($(stamp_field version)) — replacing it." >&2
  stale=1
fi

if [ ! -x ./mxcli ] || [ -n "$stale" ]; then
  # Prefer a copy that is already on this machine. Some environments ship mxcli
  # pre-installed on PATH, and the bootstrap instructions have you delete the
  # hardlink 'mxcli new' left in the project — after which this guard could
  # never be satisfied by the PATH binary and re-downloaded ~85 MB on EVERY
  # fresh session, forever. (ako/ChipCoV1)
  #
  # But never one older than the tooling: that is how a project written by a
  # newer mxcli ended up served by v0.24.0, its CLAUDE.md asking for syntax the
  # binary could not parse (ako/mxcli#952).
  #
  # Hardlink first because that is what 'mxcli new' does and it costs nothing;
  # fall back to a symlink across filesystems, then to a copy. Any of the three
  # leaves ./mxcli working, which is what the rest of this script and the
  # project's own CLAUDE.md assume.
  onpath=$(command -v mxcli 2>/dev/null || true)
  if [ -n "$onpath" ] && [ -x "$onpath" ] && [ "$onpath" != "./mxcli" ] && [ "$onpath" != "$PWD/mxcli" ]; then
    if older_than_stamp "$onpath"; then
      echo "mxcli on PATH (${onpath}) is $(bin_version "$onpath"), older than this project's tooling ($(stamp_field version)) — not linking it; downloading ${TAG} instead." >&2
    else
      echo "mxcli found on PATH (${onpath}) — linking it in rather than downloading."
      rm -f ./mxcli
      ln -f "$onpath" ./mxcli 2>/dev/null ||
        ln -sf "$onpath" ./mxcli 2>/dev/null ||
        cp "$onpath" ./mxcli
      chmod +x ./mxcli 2>/dev/null || true
      stale=
    fi
  fi
fi

if [ ! -x ./mxcli ] || [ -n "$stale" ]; then
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${TAG}/mxcli-${os}-${arch}"
  echo "Downloading mxcli ${TAG} for ${os}/${arch}..."
  # Into a temporary file, then renamed over ./mxcli: writing straight to
  # ./mxcli would write THROUGH a symlink into the PATH binary it points at,
  # and a failed download would leave no binary at all.
  if curl -fsSL -o ./mxcli.download "$url"; then
    chmod +x ./mxcli.download
    mv -f ./mxcli.download ./mxcli
  else
    rm -f ./mxcli.download
    echo "Could not download mxcli from ${url}." >&2
    if [ ! -x ./mxcli ]; then
      echo "Fetch it manually, or set MXCLI_TAG to a released version." >&2
      exit 1
    fi
    echo "Keeping the older ./mxcli; expect failures where the tooling uses newer features." >&2
  fi
fi

if older_than_stamp ./mxcli; then
  echo "WARNING: ./mxcli ($(bin_version ./mxcli)) is still older than this project's tooling ($(stamp_field version))." >&2
  echo "  Set MXCLI_TAG to $(stamp_field version) or newer (or 'nightly') and re-run this script." >&2
fi

# Keep the project's tooling (skills, bundled lint rules, the mxcli section of
# CLAUDE.md/AGENTS.md) in step with this binary. They are embedded in mxcli and
# written by 'mxcli init', so upgrading the binary used to leave yesterday's
# guidance in place with no warning — and an agent reads stale guidance with
# the same confidence as current guidance. Quiet when already current; refuses
# (rather than downgrades) when the binary is older than the tooling; never
# fatal, since a refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
`

// sessionStartHookMarkers identify OUR hook command — so re-running init updates
// it instead of duplicating it, and a user's own SessionStart hooks are never
// touched. The first is the current form; the rest are older spellings kept so
// existing projects migrate rather than accumulate a second hook.
var sessionStartHookMarkers = []string{
	bootstrapScriptName,   // current: the committed bootstrap script
	"run --local --setup", // pre-bootstrap-script: the command inlined in the hook
}

// isMxcliSessionStartHook reports whether a hook command is one mxcli wrote.
func isMxcliSessionStartHook(command string) bool {
	for _, m := range sessionStartHookMarkers {
		if strings.Contains(command, m) {
			return true
		}
	}
	return false
}

// sessionStartHookCommand is the shell command the hook runs. It delegates to a
// committed script rather than inlining the work, for two reasons:
//
//  1. The inlined form was guarded on `test -x ./mxcli`, and the binary it
//     guards on is git-ignored (~85 MB, deliberately). In an ephemeral container
//     the repo is re-cloned after an idle reap, `./mxcli` is not in the clone,
//     the guard fails and the hook silently no-ops through `|| true` — leaving
//     exactly the unprepared session the hook exists to prevent, with no error
//     saying so. The script can fetch the binary back; a hook line cannot
//     reasonably do OS/arch detection. (mxcli-todo findings #2)
//  2. The command string stays constant, so re-running `mxcli init` recognises
//     its own hook even when the project is renamed.
func sessionStartHookCommand() string {
	return fmt.Sprintf("sh %s || true", bootstrapScriptName)
}

// ensureSessionStartHook adds (idempotently) the mxcli bring-up to
// .claude/settings.json, preserving any existing settings/hooks. It returns
// whether a change was written. If settings.json exists but is not valid JSON it
// is left untouched (changed=false) with an error, so we never destroy content.
func ensureSessionStartHook(claudeDir, mprFile string) (changed bool, err error) {
	path := filepath.Join(claudeDir, "settings.json")

	// The script is rewritten every time so a renamed .mpr (or an improvement to
	// the script itself) is picked up; it holds no user content.
	scriptChanged, err := writeBootstrapScript(claudeDir, mprFile)
	if err != nil {
		return false, err
	}

	settings := map[string]any{}
	if data, readErr := os.ReadFile(path); readErr == nil {
		if json.Unmarshal(data, &settings) != nil {
			return scriptChanged, fmt.Errorf("%s exists but is not valid JSON; leaving it untouched — add a SessionStart hook manually", path)
		}
	}

	if updated := addSessionStartHook(settings, sessionStartHookCommand()); !updated {
		return scriptChanged, nil // hook already current
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return false, err
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// writeBootstrapScript writes (or refreshes) the committed bootstrap script the
// SessionStart hook runs. Reports whether the content changed.
func writeBootstrapScript(claudeDir, mprFile string) (changed bool, err error) {
	// claudeDir is <project>/.claude and bootstrapScriptName is project-relative,
	// so take the base name to land beside settings.json.
	path := filepath.Join(claudeDir, filepath.Base(bootstrapScriptName))
	want := []byte(fmt.Sprintf(bootstrapScriptTemplate, mprFile))
	if existing, readErr := os.ReadFile(path); readErr == nil && bytes.Equal(existing, want) {
		return false, nil
	}
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, want, 0o755); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

// addSessionStartHook inserts a SessionStart command hook into a parsed settings
// map, preserving existing keys and hooks. An entry matching any known marker is
// UPDATED in place rather than duplicated, so a project written by an older
// mxcli (which inlined the whole command) migrates to the current one instead of
// ending up with two hooks that both run. Returns whether anything changed.
// Operates on the generic JSON shape so it never drops unknown settings.
func addSessionStartHook(settings map[string]any, command string) bool {
	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}
	sessionStart, _ := hooks["SessionStart"].([]any)

	for _, entry := range sessionStart {
		em, ok := entry.(map[string]any)
		if !ok {
			continue
		}
		inner, _ := em["hooks"].([]any)
		for _, h := range inner {
			hm, ok := h.(map[string]any)
			if !ok {
				continue
			}
			c, _ := hm["command"].(string)
			if !isMxcliSessionStartHook(c) {
				continue
			}
			if c == command {
				return false // already current
			}
			hm["command"] = command
			settings["hooks"] = hooks
			return true
		}
	}

	sessionStart = append(sessionStart, map[string]any{
		"hooks": []any{
			map[string]any{"type": "command", "command": command},
		},
	})
	hooks["SessionStart"] = sessionStart
	settings["hooks"] = hooks
	return true
}
