// SPDX-License-Identifier: Apache-2.0

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

// tooling_stamp.go records which mxcli wrote a project's tooling, and warns
// when a binary older than that one opens the project (ako/mxcli#952).
//
// The failure it exists for: a project's CLAUDE.md asked for `mdl 1;` and its
// lint rules read `document_noun`, both written by a newer mxcli than the
// v0.24.0 on PATH. Every one of those then failed — a parse error, three
// crashing rules counted as project errors — and nothing said the cause was the
// binary rather than the project, because nothing recorded which mxcli had
// written the tooling.
//
// A binary can only warn about a stamp it knows to read, so a binary that
// predates the stamp (v0.24.0 and everything before it) stays silent whatever
// the stamp says. That is why the bootstrap script checks the version too: it
// runs before the binary is chosen, and it is regenerated by the newer mxcli
// that writes the stamp.

// toolingStampRel is the stamp's path relative to the project directory. It
// lives in .ai-context/, which every --tool receives, rather than .claude/,
// which only Claude Code projects have.
const toolingStampRel = ".ai-context/mxcli-tooling.json"

// toolingStamp is the content of the stamp file.
type toolingStamp struct {
	// Version is the mxcli version that last wrote the tooling, exactly as
	// `mxcli --version` reports it (v0.25.0, nightly-20261002-4ba1495f2,
	// v0.24.0-888-g4ba1495f2 for a dev build).
	Version string `json:"version"`
	// Built is that binary's build time (RFC 3339), when it had one. It is
	// what lets a release and a nightly be ordered against each other.
	Built string `json:"built,omitempty"`
	// Written is the date the stamp was (re)written, YYYY-MM-DD.
	Written string `json:"written"`
}

// currentMxcliVersion is the running binary's version as the stamp records
// it. A build without -X main.Version has no meaningful version at all.
func currentMxcliVersion() string {
	if Version == "" {
		return "unknown"
	}
	return Version
}

// readToolingStamp returns the project's stamp, or nil when there is none (or
// it is unreadable — a broken stamp must never stop a command).
func readToolingStamp(projectDir string) *toolingStamp {
	data, err := os.ReadFile(filepath.Join(projectDir, toolingStampRel))
	if err != nil {
		return nil
	}
	var s toolingStamp
	if json.Unmarshal(data, &s) != nil || s.Version == "" {
		return nil
	}
	return &s
}

// writeToolingStamp records the running binary as the writer of the project's
// tooling. It rewrites nothing when the stamp already names this version, so a
// sync on every session start does not dirty the working tree once a day.
func writeToolingStamp(projectDir string) (changed bool, err error) {
	cur := currentMxcliVersion()
	if old := readToolingStamp(projectDir); old != nil && old.Version == cur {
		return false, nil
	}
	s := toolingStamp{Version: cur, Built: BuildTime, Written: time.Now().UTC().Format("2006-01-02")}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return false, err
	}
	path := filepath.Join(projectDir, toolingStampRel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

// versionKind classifies an mxcli version string.
type versionKind int

const (
	versionUnknown versionKind = iota // dev build, untagged, or unparseable
	versionRelease                    // v0.24.0
	versionNightly                    // nightly-20261002-4ba1495f2
)

type mxcliVersion struct {
	kind  versionKind
	parts [3]int // release only
	date  string // nightly only: YYYYMMDD
}

var (
	releaseVersionRe = regexp.MustCompile(`^v?(\d+)\.(\d+)\.(\d+)$`)
	nightlyVersionRe = regexp.MustCompile(`^nightly-(\d{8})-[0-9a-f]+$`)
	buildDateRe      = regexp.MustCompile(`^(\d{4})-(\d{2})-(\d{2})T`)
)

// parseMxcliVersion classifies a version. Anything that is not exactly a
// release tag or a nightly tag — `git describe` output such as
// v0.24.0-888-g4ba1495f2, a -dirty build, "unknown" — is versionUnknown, and an
// unknown version is never compared: a dev build is whatever its author made
// it, and guessing an order for it would warn about nothing or miss real skew.
func parseMxcliVersion(v string) mxcliVersion {
	v = strings.TrimSpace(v)
	if i := strings.IndexByte(v, ' '); i >= 0 { // "v0.24.0 (2026-…)" from --version
		v = v[:i]
	}
	if m := releaseVersionRe.FindStringSubmatch(v); m != nil {
		var out mxcliVersion
		out.kind = versionRelease
		for i := 0; i < 3; i++ {
			out.parts[i], _ = strconv.Atoi(m[i+1])
		}
		return out
	}
	if m := nightlyVersionRe.FindStringSubmatch(v); m != nil {
		return mxcliVersion{kind: versionNightly, date: m[1]}
	}
	return mxcliVersion{}
}

// buildDate turns an RFC 3339 build time into YYYYMMDD, or "".
func buildDate(built string) string {
	m := buildDateRe.FindStringSubmatch(built)
	if m == nil {
		return ""
	}
	return m[1] + m[2] + m[3]
}

// binaryOlderThan reports whether a binary (version + build time) is provably
// older than the one that wrote the stamp. "Provably" is the operative word:
// with either side unknown the answer is false.
//
//   - two releases compare by version number;
//   - two nightlies compare by the date in the tag;
//   - a release against a nightly compares build dates, since neither number
//     orders the other — and says nothing when a build date is missing.
//
// Dates are compared by day, so a release and a nightly from the same day are
// never reported as skewed.
//
// The bootstrap script carries a POSIX-sh copy of these rules (vclass /
// version_lt in bootstrapScriptTemplate); TestBootstrapVersionGuard holds the
// two together.
func binaryOlderThan(binVersion, binBuilt string, stamp toolingStamp) bool {
	b := parseMxcliVersion(binVersion)
	s := parseMxcliVersion(stamp.Version)
	if b.kind == versionUnknown || s.kind == versionUnknown {
		return false
	}
	if b.kind == versionRelease && s.kind == versionRelease {
		for i := 0; i < 3; i++ {
			if b.parts[i] != s.parts[i] {
				return b.parts[i] < s.parts[i]
			}
		}
		return false
	}
	bd, sd := b.date, s.date
	if b.kind == versionRelease {
		bd = buildDate(binBuilt)
	}
	if s.kind == versionRelease {
		sd = buildDate(stamp.Built)
	}
	if bd == "" || sd == "" {
		return false
	}
	return bd < sd
}

// staleBinaryStamp returns the project's stamp when the running binary is
// older than it, else nil.
func staleBinaryStamp(projectDir string) *toolingStamp {
	s := readToolingStamp(projectDir)
	if s == nil || !binaryOlderThan(Version, BuildTime, *s) {
		return nil
	}
	return s
}

// updateTag is the release tag to fetch for a stamp version: a nightly is only
// ever available as the rolling "nightly" release.
func updateTag(stampVersion string) string {
	if parseMxcliVersion(stampVersion).kind == versionNightly {
		return "nightly"
	}
	return stampVersion
}

// writeStaleBinaryWarning explains the skew: both versions, what goes wrong,
// and how to update.
func writeStaleBinaryWarning(w io.Writer, s toolingStamp) {
	fmt.Fprintf(w, "Warning: this project's mxcli tooling (CLAUDE.md, skills, lint rules) was written by mxcli %s,\n", s.Version)
	fmt.Fprintf(w, "  but this binary is %s. Statements, commands and lint-rule fields the tooling uses may not exist here.\n", currentMxcliVersion())
	fmt.Fprintf(w, "  Update: ./mxcli setup mxcli --tag %s --output ./mxcli (add --os/--arch off linux/amd64),\n", updateTag(s.Version))
	fmt.Fprintf(w, "  or delete ./mxcli and re-run: sh %s\n", bootstrapScriptName)
}

var toolingWarnOnce sync.Once

// warnIfToolingNewer prints the skew warning at most once per process. It
// takes the -p value: a .mpr path or a project directory.
func warnIfToolingNewer(w io.Writer, projectPath string) {
	if projectPath == "" {
		return
	}
	dir := projectPath
	if st, err := os.Stat(projectPath); err != nil || !st.IsDir() {
		dir = filepath.Dir(projectPath)
	}
	s := staleBinaryStamp(dir)
	if s == nil {
		return
	}
	toolingWarnOnce.Do(func() { writeStaleBinaryWarning(w, *s) })
}
