// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/mendixlabs/mxcli/mdl/ast"
	"github.com/mendixlabs/mxcli/mdl/backend/mock"
	"github.com/mendixlabs/mxcli/mdl/types"
	"github.com/mendixlabs/mxcli/model"
)

// A Studio Pro .js source holds three things MDL cannot print: the import
// list, the EXTRA CODE section (describe shows it only as `--` comments) and
// the function signature Studio Pro generated. Regenerating the file from the
// statement drops all three — NanoflowCommons.GetStraightLineDistance lost
// `import { Big }` and the deg2rad helpers its user code calls.
const storedGetDistanceJS = `// This file was generated by Mendix Studio Pro.
import { Big } from "big.js";

// BEGIN EXTRA CODE
function deg2rad(deg) {
    return deg.times(Math.PI / 180);
}
// END EXTRA CODE

/**
 * @param {Big} latitude
 * @returns {Promise.<Big>}
 */
export async function GetDistance(latitude) {
	// BEGIN USER CODE
    return deg2rad(latitude);
	// END USER CODE
}
`

// Since describe emits `create or modify javascript action` (#731), running its
// output unchanged reaches the rewrite. A statement whose code is the stored
// user code, with the stored parameters, says nothing new about the source, so
// the file is left alone. Changing the code or the parameter list still
// regenerates it (the controls).
func TestJavaScriptActionRewrite_UnchangedCodeKeepsSourceFile(t *testing.T) {
	dir := t.TempDir()
	mprPath := filepath.Join(dir, "App.mpr")
	jsDir := filepath.Join(dir, "javascriptsource", "webmod", "actions")
	if err := os.MkdirAll(jsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(jsDir, "GetDistance.js"), []byte(storedGetDistanceJS), 0o644); err != nil {
		t.Fatal(err)
	}

	mod := mkModule("WebMod")
	h := mkHierarchy(mod)
	stored := &types.JavaScriptAction{
		BaseElement: model.BaseElement{ID: nextID("jsa")},
		ContainerID: mod.ID,
		Name:        "GetDistance",
		Parameters: []*types.JavaActionParameter{{
			Name: "latitude", IsRequired: true, ParameterType: &types.DecimalType{},
		}},
	}
	withContainer(h, stored.ContainerID, mod.ID)
	wrote := 0
	mb := &mock.MockBackend{
		IsConnectedFunc:                func() bool { return true },
		ListModulesFunc:                func() ([]*model.Module, error) { return []*model.Module{mod}, nil },
		ListJavaScriptActionsFunc:      func() ([]*types.JavaScriptAction, error) { return []*types.JavaScriptAction{stored}, nil },
		ReadJavaScriptActionByNameFunc: func(string) (*types.JavaScriptAction, error) { return stored, nil },
		UpdateJavaScriptActionFunc:     func(*types.JavaScriptAction) error { return nil },
		WriteJavaScriptSourceFileFunc: func(string, string, string, []*types.JavaActionParameter, types.CodeActionReturnType) error {
			wrote++
			return nil
		},
	}
	ctx, _ := newMockCtx(t, withBackend(mb), withHierarchy(h), withMprPath(mprPath))

	// The body exactly as describe prints it.
	userCode, _ := readJavaScriptActionSource(mprPath, "WebMod", "GetDistance")
	if userCode == "" {
		t.Fatal("precondition: the stored user code was not read")
	}
	stmt := func(code string, params ...string) *ast.CreateJavaScriptActionStmt {
		s := &ast.CreateJavaScriptActionStmt{
			Name:           ast.QualifiedName{Module: "WebMod", Name: "GetDistance"},
			CreateOrModify: true,
			ReturnType:     ast.DataType{Kind: ast.TypeDecimal},
			JavaScriptCode: code,
		}
		for _, p := range params {
			s.Parameters = append(s.Parameters, ast.JavaActionParam{Name: p, Type: ast.DataType{Kind: ast.TypeDecimal}, IsRequired: true})
		}
		return s
	}

	assertNoError(t, execCreateJavaScriptAction(ctx, stmt("\n"+userCode+"\n", "latitude")))
	if wrote != 0 {
		t.Fatal("unchanged describe output regenerated the .js source, dropping its imports and EXTRA CODE")
	}

	// Control: edited code is written.
	assertNoError(t, execCreateJavaScriptAction(ctx, stmt("return latitude;", "latitude")))
	if wrote != 1 {
		t.Errorf("edited code was not written (writes: %d)", wrote)
	}
	// Control: a changed parameter list regenerates the signature.
	assertNoError(t, execCreateJavaScriptAction(ctx, stmt(userCode, "latitude", "longitude")))
	if wrote != 2 {
		t.Errorf("a changed parameter list was not written (writes: %d)", wrote)
	}
}
